import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import Navbar from "@/components/custom/navbar";
import Footer from "@/components/custom/footer";
import Providers from "@/components/providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      <Providers>
        <Navbar/>
          <main>
            {children}
          </main>
        <Footer/>  
        <Toaster />
      </Providers>
      </body>
    </html>
  );
}
